apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-ai-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mnist-ai
  template:
    metadata:
      labels:
        app: mnist-ai
    spec:
      containers:
        - name: mnist-ai-container
        image: mnist-ai:latest
        imagePullPolicy: Never 
